// Code generated by protoc-gen-go and protoc-gen-go-grpc. DO NOT EDIT.
// Regenerate with:
//   protoc --go_out=. --go_opt=paths=source_relative \
//          --go-grpc_out=. --go-grpc_opt=paths=source_relative \
//          proto/raft.proto

package proto

import (
	"context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	"google.golang.org/protobuf/runtime/protoimpl"
)

// ── Message types ──────────────────────────────────────────────────────────

type RequestVoteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Term         uint64 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	CandidateId  string `protobuf:"bytes,2,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	LastLogIndex uint64 `protobuf:"varint,3,opt,name=last_log_index,json=lastLogIndex,proto3" json:"last_log_index,omitempty"`
	LastLogTerm  uint64 `protobuf:"varint,4,opt,name=last_log_term,json=lastLogTerm,proto3" json:"last_log_term,omitempty"`
}

func (x *RequestVoteRequest) Reset()         { *x = RequestVoteRequest{} }
func (x *RequestVoteRequest) String() string { return "" }
func (*RequestVoteRequest) ProtoMessage()    {}

func (x *RequestVoteRequest) GetTerm() uint64         { return x.Term }
func (x *RequestVoteRequest) GetCandidateId() string  { return x.CandidateId }
func (x *RequestVoteRequest) GetLastLogIndex() uint64 { return x.LastLogIndex }
func (x *RequestVoteRequest) GetLastLogTerm() uint64  { return x.LastLogTerm }

type RequestVoteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Term        uint64 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	VoteGranted bool   `protobuf:"varint,2,opt,name=vote_granted,json=voteGranted,proto3" json:"vote_granted,omitempty"`
}

func (x *RequestVoteResponse) Reset()         { *x = RequestVoteResponse{} }
func (x *RequestVoteResponse) String() string { return "" }
func (*RequestVoteResponse) ProtoMessage()    {}

func (x *RequestVoteResponse) GetTerm() uint64       { return x.Term }
func (x *RequestVoteResponse) GetVoteGranted() bool  { return x.VoteGranted }

type LogEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index   uint64 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Term    uint64 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Command []byte `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
}

func (x *LogEntry) Reset()         { *x = LogEntry{} }
func (x *LogEntry) String() string { return "" }
func (*LogEntry) ProtoMessage()    {}

func (x *LogEntry) GetIndex() uint64   { return x.Index }
func (x *LogEntry) GetTerm() uint64    { return x.Term }
func (x *LogEntry) GetCommand() []byte { return x.Command }

type AppendEntriesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Term         uint64      `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId     string      `protobuf:"bytes,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	PrevLogIndex uint64      `protobuf:"varint,3,opt,name=prev_log_index,json=prevLogIndex,proto3" json:"prev_log_index,omitempty"`
	PrevLogTerm  uint64      `protobuf:"varint,4,opt,name=prev_log_term,json=prevLogTerm,proto3" json:"prev_log_term,omitempty"`
	Entries      []*LogEntry `protobuf:"bytes,5,rep,name=entries,proto3" json:"entries,omitempty"`
	LeaderCommit uint64      `protobuf:"varint,6,opt,name=leader_commit,json=leaderCommit,proto3" json:"leader_commit,omitempty"`
}

func (x *AppendEntriesRequest) Reset()         { *x = AppendEntriesRequest{} }
func (x *AppendEntriesRequest) String() string { return "" }
func (*AppendEntriesRequest) ProtoMessage()    {}

func (x *AppendEntriesRequest) GetTerm() uint64           { return x.Term }
func (x *AppendEntriesRequest) GetLeaderId() string       { return x.LeaderId }
func (x *AppendEntriesRequest) GetPrevLogIndex() uint64   { return x.PrevLogIndex }
func (x *AppendEntriesRequest) GetPrevLogTerm() uint64    { return x.PrevLogTerm }
func (x *AppendEntriesRequest) GetEntries() []*LogEntry   { return x.Entries }
func (x *AppendEntriesRequest) GetLeaderCommit() uint64   { return x.LeaderCommit }

type AppendEntriesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Term    uint64 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Success bool   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *AppendEntriesResponse) Reset()         { *x = AppendEntriesResponse{} }
func (x *AppendEntriesResponse) String() string { return "" }
func (*AppendEntriesResponse) ProtoMessage()    {}

func (x *AppendEntriesResponse) GetTerm() uint64    { return x.Term }
func (x *AppendEntriesResponse) GetSuccess() bool   { return x.Success }

// ── gRPC client ────────────────────────────────────────────────────────────

type RaftServiceClient interface {
	RequestVote(ctx context.Context, in *RequestVoteRequest, opts ...grpc.CallOption) (*RequestVoteResponse, error)
	AppendEntries(ctx context.Context, in *AppendEntriesRequest, opts ...grpc.CallOption) (*AppendEntriesResponse, error)
}

type raftServiceClient struct{ cc grpc.ClientConnInterface }

func NewRaftServiceClient(cc grpc.ClientConnInterface) RaftServiceClient {
	return &raftServiceClient{cc}
}

func (c *raftServiceClient) RequestVote(ctx context.Context, in *RequestVoteRequest, opts ...grpc.CallOption) (*RequestVoteResponse, error) {
	out := new(RequestVoteResponse)
	err := c.cc.Invoke(ctx, "/raft.RaftService/RequestVote", in, out, opts...)
	return out, err
}

func (c *raftServiceClient) AppendEntries(ctx context.Context, in *AppendEntriesRequest, opts ...grpc.CallOption) (*AppendEntriesResponse, error) {
	out := new(AppendEntriesResponse)
	err := c.cc.Invoke(ctx, "/raft.RaftService/AppendEntries", in, out, opts...)
	return out, err
}

// ── gRPC server ────────────────────────────────────────────────────────────

type RaftServiceServer interface {
	RequestVote(context.Context, *RequestVoteRequest) (*RequestVoteResponse, error)
	AppendEntries(context.Context, *AppendEntriesRequest) (*AppendEntriesResponse, error)
	mustEmbedUnimplementedRaftServiceServer()
}

type UnimplementedRaftServiceServer struct{}

func (UnimplementedRaftServiceServer) RequestVote(context.Context, *RequestVoteRequest) (*RequestVoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "RequestVote not implemented")
}
func (UnimplementedRaftServiceServer) AppendEntries(context.Context, *AppendEntriesRequest) (*AppendEntriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "AppendEntries not implemented")
}
func (UnimplementedRaftServiceServer) mustEmbedUnimplementedRaftServiceServer() {}

func RegisterRaftServiceServer(s grpc.ServiceRegistrar, srv RaftServiceServer) {
	s.RegisterService(&RaftService_ServiceDesc, srv)
}

func _RaftService_RequestVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestVoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServiceServer).RequestVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/raft.RaftService/RequestVote"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServiceServer).RequestVote(ctx, req.(*RequestVoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftService_AppendEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServiceServer).AppendEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/raft.RaftService/AppendEntries"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServiceServer).AppendEntries(ctx, req.(*AppendEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var RaftService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "raft.RaftService",
	HandlerType: (*RaftServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "RequestVote", Handler: _RaftService_RequestVote_Handler},
		{MethodName: "AppendEntries", Handler: _RaftService_AppendEntries_Handler},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/raft.proto",
}
